# Generated by Django 4.2.4 on 2024-02-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quesctin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quesctin_text', models.CharField(max_length=200)),
                ('pub_date', models.DateField(verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('Quesctin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.quesctin')),
            ],
        ),
    ]
