# Generated by Django 4.2.4 on 2024-02-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesctin',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
